[2023-04-29T06:28:43.779+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: Transform.wait_for_extraction manual__2023-04-29T06:28:39.150311+00:00 [queued]>
[2023-04-29T06:28:43.828+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: Transform.wait_for_extraction manual__2023-04-29T06:28:39.150311+00:00 [queued]>
[2023-04-29T06:28:43.831+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-04-29T06:28:43.914+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2023-04-29T06:28:43.915+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-04-29T06:28:44.043+0000] {taskinstance.py:1304} INFO - Executing <Task(ExternalTaskSensor): wait_for_extraction> on 2023-04-29 06:28:39.150311+00:00
[2023-04-29T06:28:44.061+0000] {standard_task_runner.py:55} INFO - Started process 91 to run task
[2023-04-29T06:28:44.066+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Transform', 'wait_for_extraction', 'manual__2023-04-29T06:28:39.150311+00:00', '--job-id', '234', '--raw', '--subdir', 'DAGS_FOLDER/Dag.py', '--cfg-path', '/tmp/tmpfzdci0t3']
[2023-04-29T06:28:44.073+0000] {standard_task_runner.py:83} INFO - Job 234: Subtask wait_for_extraction
[2023-04-29T06:28:44.559+0000] {task_command.py:389} INFO - Running <TaskInstance: Transform.wait_for_extraction manual__2023-04-29T06:28:39.150311+00:00 [running]> on host 46ac91bb69b9
[2023-04-29T06:28:46.334+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Lina Arroyo
AIRFLOW_CTX_DAG_ID=Transform
AIRFLOW_CTX_TASK_ID=wait_for_extraction
AIRFLOW_CTX_EXECUTION_DATE=2023-04-29T06:28:39.150311+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-29T06:28:39.150311+00:00
[2023-04-29T06:28:46.338+0000] {external_task.py:203} INFO - Poking for tasks ['extract'] in dag Extract on 2023-04-29T06:28:39.150311+00:00 ... 
[2023-04-29T06:29:46.421+0000] {external_task.py:203} INFO - Poking for tasks ['extract'] in dag Extract on 2023-04-29T06:28:39.150311+00:00 ... 
[2023-04-29T06:30:46.491+0000] {external_task.py:203} INFO - Poking for tasks ['extract'] in dag Extract on 2023-04-29T06:28:39.150311+00:00 ... 
[2023-04-29T06:31:46.563+0000] {external_task.py:203} INFO - Poking for tasks ['extract'] in dag Extract on 2023-04-29T06:28:39.150311+00:00 ... 
[2023-04-29T06:32:46.634+0000] {external_task.py:203} INFO - Poking for tasks ['extract'] in dag Extract on 2023-04-29T06:28:39.150311+00:00 ... 
[2023-04-29T06:33:46.706+0000] {external_task.py:203} INFO - Poking for tasks ['extract'] in dag Extract on 2023-04-29T06:28:39.150311+00:00 ... 
[2023-04-29T06:34:46.781+0000] {external_task.py:203} INFO - Poking for tasks ['extract'] in dag Extract on 2023-04-29T06:28:39.150311+00:00 ... 
[2023-04-29T06:35:46.855+0000] {external_task.py:203} INFO - Poking for tasks ['extract'] in dag Extract on 2023-04-29T06:28:39.150311+00:00 ... 
[2023-04-29T06:36:46.921+0000] {external_task.py:203} INFO - Poking for tasks ['extract'] in dag Extract on 2023-04-29T06:28:39.150311+00:00 ... 
[2023-04-29T06:37:46.993+0000] {external_task.py:203} INFO - Poking for tasks ['extract'] in dag Extract on 2023-04-29T06:28:39.150311+00:00 ... 
[2023-04-29T06:38:47.028+0000] {external_task.py:203} INFO - Poking for tasks ['extract'] in dag Extract on 2023-04-29T06:28:39.150311+00:00 ... 
[2023-04-29T06:39:47.115+0000] {external_task.py:203} INFO - Poking for tasks ['extract'] in dag Extract on 2023-04-29T06:28:39.150311+00:00 ... 
[2023-04-29T06:40:47.181+0000] {external_task.py:203} INFO - Poking for tasks ['extract'] in dag Extract on 2023-04-29T06:28:39.150311+00:00 ... 
[2023-04-29T06:41:04.886+0000] {local_task_job.py:223} WARNING - State of this instance has been externally set to None. Terminating instance.
[2023-04-29T06:41:04.892+0000] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 91. PIDs of all processes in the group: [91]
[2023-04-29T06:41:04.893+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 91
[2023-04-29T06:41:04.894+0000] {taskinstance.py:1483} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-04-29T06:41:04.906+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/sensors/base.py", line 226, in execute
    time.sleep(self._get_next_poke_interval(started_at, run_duration, try_number))
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1485, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2023-04-29T06:41:04.915+0000] {taskinstance.py:1322} INFO - Marking task as FAILED. dag_id=Transform, task_id=wait_for_extraction, execution_date=20230429T062839, start_date=20230429T062843, end_date=20230429T064104
[2023-04-29T06:41:05.133+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 234 for task wait_for_extraction ((psycopg2.errors.ForeignKeyViolation) insert or update on table "task_fail" violates foreign key constraint "task_fail_ti_fkey"
DETAIL:  Key (dag_id, task_id, run_id, map_index)=(Transform, wait_for_extraction, manual__2023-04-29T06:28:39.150311+00:00, -1) is not present in table "task_instance".

[SQL: INSERT INTO task_fail (task_id, dag_id, run_id, map_index, start_date, end_date, duration) VALUES (%(task_id)s, %(dag_id)s, %(run_id)s, %(map_index)s, %(start_date)s, %(end_date)s, %(duration)s) RETURNING task_fail.id]
[parameters: {'task_id': 'wait_for_extraction', 'dag_id': 'Transform', 'run_id': 'manual__2023-04-29T06:28:39.150311+00:00', 'map_index': -1, 'start_date': datetime.datetime(2023, 4, 29, 6, 28, 43, 790084, tzinfo=Timezone('UTC')), 'end_date': datetime.datetime(2023, 4, 29, 6, 41, 4, 914122, tzinfo=Timezone('UTC')), 'duration': 741}]
(Background on this error at: https://sqlalche.me/e/14/gkpj); 91)
[2023-04-29T06:41:05.201+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=91, status='terminated', exitcode=1, started='06:28:43') (91) terminated with exit code 1
